name: build-windows-exe

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE (onefile, no console)
        run: |
          pyinstaller --noconsole --onefile --name ChromPeaksGUI chrom_peaks_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChromPeaksGUI-windows
          path: dist/ChromPeaksGUI.exe
